typography_spectrum: 0.8270600833930075
color:
  brandStrength: 0.10784916835837066
  lightness: 0.747202011058107
  saturation: 0.9083300612401217
  rhythmicContrast: 0.3088306770659983
  brandColors:
    - '#F7F3F0'
    - '#8FB4CE'
    - '#012F49'
    - '#3E5567'
    - '#8F8785'
layout_spectrum: 0.9895118924323469
name: Emineo Media
description: Driving Real Business Growth
